Comented out root check for Dockerfile
This is still testing, I don't know what I'm doing.

diff --git a/digital-cinema-tools-setup b/digital-cinema-tools-setup
--- a/digital-cinema-tools-setup
+++ b/digital-cinema-tools-setup
@@ -129,25 +129,25 @@ fi
 
 
 # Check and bail out if the installer is run with root privileges
-if [ $script_runner == "root" ]
-then
-  echo
-  echo 'Do not run this installer as root'
-  echo 'Do not run this installer via sudo'
-  echo 'This installer will ask for privileges if and when required'
-  echo
-  echo 'That said:'
-  echo
-  echo 'If you know exactly why you would want to'
-  echo "continue as root -- usually you don't want to --"
-  read -p 'then type root and press [ENTER]: ' run_as_root_confirm
-  if ! [ "$run_as_root_confirm" == "root" ]
-  then
-    exit 1
-  fi
-  echo 'Continuing as root ...'
-  sleep 3
-fi
+#if [ $script_runner == "root" ]
+#then
+#  echo
+#  echo 'Do not run this installer as root'
+#  echo 'Do not run this installer via sudo'
+#  echo 'This installer will ask for privileges if and when required'
+#  echo
+#  echo 'That said:'
+#  echo
+#  echo 'If you know exactly why you would want to'
+#  echo "continue as root -- usually you don't want to --"
+#  read -p 'then type root and press [ENTER]: ' run_as_root_confirm
+#  if ! [ "$run_as_root_confirm" == "root" ]
+#  then
+#    exit 1
+#  fi
+#  echo 'Continuing as root ...'
+#  sleep 3
+#fi
 
 
 #
